package github.changweitu.com.an.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import github.changweitu.com.an.model.TopicEntity;
import github.changweitu.com.an.model.UserEntity;

import github.changweitu.com.an.model.TopicEntityDao;
import github.changweitu.com.an.model.UserEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig topicEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;

    private final TopicEntityDao topicEntityDao;
    private final UserEntityDao userEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        topicEntityDaoConfig = daoConfigMap.get(TopicEntityDao.class).clone();
        topicEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        topicEntityDao = new TopicEntityDao(topicEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);

        registerDao(TopicEntity.class, topicEntityDao);
        registerDao(UserEntity.class, userEntityDao);
    }
    
    public void clear() {
        topicEntityDaoConfig.getIdentityScope().clear();
        userEntityDaoConfig.getIdentityScope().clear();
    }

    public TopicEntityDao getTopicEntityDao() {
        return topicEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

}
